/* Generated By:JavaCC: Do not edit this line. AtlParserTreeConstants.java Version 6.0_1 */
package org.lmind.atl.core.ast;

public interface AtlParserTreeConstants
{
  public int JJTBODY = 0;
  public int JJTDIRECTIVES = 1;
  public int JJTDOMAIN = 2;
  public int JJTDIRECTIVESBODY = 3;


  public String[] jjtNodeName = {
    "Body",
    "Directives",
    "Domain",
    "DirectivesBody",
  };
}
/* JavaCC - OriginalChecksum=a57e9c693b591200acde53ddad4156d2 (do not edit this line) */
