/* Generated By:JJTree&JavaCC: Do not edit this line. AtlParserConstants.java */
package org.lmind.atl.core.ast;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AtlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TEXT = 5;
  /** RegularExpression Id. */
  int TEXT_NODE = 6;
  /** RegularExpression Id. */
  int STRING_LITERAL = 7;
  /** RegularExpression Id. */
  int TEXT_LITERAL = 8;
  /** RegularExpression Id. */
  int DOMAIN = 9;
  /** RegularExpression Id. */
  int IDENTIFIER = 10;
  /** RegularExpression Id. */
  int LETTER = 11;
  /** RegularExpression Id. */
  int DIGIT = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<TEXT>",
    "<TEXT_NODE>",
    "<STRING_LITERAL>",
    "<TEXT_LITERAL>",
    "<DOMAIN>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"#\"",
  };

}
