/* Generated By:JavaCC: Do not edit this line. JelParserTreeConstants.java Version 6.0_1 */
package org.lmind.jel.core.ast;

public interface JelParserTreeConstants
{
  public int JJTBOOLEANLITERAL = 0;
  public int JJTNULLLITERAL = 1;
  public int JJTSTRINGLITERAL = 2;
  public int JJTNUMBERLITERAL = 3;
  public int JJTVOID = 4;
  public int JJTIDENTIFIER = 5;
  public int JJTEXPRESSION = 6;
  public int JJTTERNARYEXPRESSION = 7;
  public int JJTOREXPRESSION = 8;
  public int JJTANDEXPRESSION = 9;
  public int JJTEQUALSEXPRESSION = 10;
  public int JJTNOTEQUALSEXPRESSION = 11;
  public int JJTLESSEREXPRESSION = 12;
  public int JJTGREATEREXPRESSION = 13;
  public int JJTLESSEREQUALSEXPRESSION = 14;
  public int JJTGREATEREQUALSEXPRESSION = 15;
  public int JJTADDEXPRESSION = 16;
  public int JJTSUBEXPRESSION = 17;
  public int JJTMULTIPLYEXPRESSION = 18;
  public int JJTDIVISIONEXPRESSION = 19;
  public int JJTMODEXPRESSION = 20;
  public int JJTNEGATEEXPRESSION = 21;
  public int JJTUNARYEXPRESSIONNOT = 22;
  public int JJTPROPERTYREADEXPRESSION = 23;
  public int JJTINDEXPROPERTYREADEXPRESSION = 24;
  public int JJTCALLEXPRESSION = 25;
  public int JJTCALLPARAMETERSEXPRESSION = 26;
  public int JJTREFERENCE = 27;


  public String[] jjtNodeName = {
    "BooleanLiteral",
    "NullLiteral",
    "StringLiteral",
    "NumberLiteral",
    "void",
    "Identifier",
    "Expression",
    "TernaryExpression",
    "OrExpression",
    "AndExpression",
    "EqualsExpression",
    "NotEqualsExpression",
    "LesserExpression",
    "GreaterExpression",
    "LesserEqualsExpression",
    "GreaterEqualsExpression",
    "AddExpression",
    "SubExpression",
    "MultiplyExpression",
    "DivisionExpression",
    "ModExpression",
    "NegateExpression",
    "UnaryExpressionNot",
    "PropertyReadExpression",
    "IndexPropertyReadExpression",
    "CallExpression",
    "CallParametersExpression",
    "Reference",
  };
}
/* JavaCC - OriginalChecksum=613d05c94d712e740c086a83451f86c0 (do not edit this line) */
