/* Generated By:JavaCC: Do not edit this line. JelParserTreeConstants.java Version 6.0_1 */
package org.lmind.jel.core.ast;

public interface JelParserTreeConstants
{
  public int JJTBOOLEANLITERAL = 0;
  public int JJTNULLLITERAL = 1;
  public int JJTSTRINGLITERAL = 2;
  public int JJTNUMBERLITERAL = 3;
  public int JJTVOID = 4;
  public int JJTIDENTIFIER = 5;
  public int JJTEXPRESSION = 6;
  public int JJTSETEXPRESSION = 7;
  public int JJTSETITEMEXPRESSION = 8;
  public int JJTTERNARYEXPRESSION = 9;
  public int JJTOREXPRESSION = 10;
  public int JJTANDEXPRESSION = 11;
  public int JJTEQUALSEXPRESSION = 12;
  public int JJTNOTEQUALSEXPRESSION = 13;
  public int JJTLESSEREXPRESSION = 14;
  public int JJTGREATEREXPRESSION = 15;
  public int JJTLESSEREQUALSEXPRESSION = 16;
  public int JJTGREATEREQUALSEXPRESSION = 17;
  public int JJTADDEXPRESSION = 18;
  public int JJTSUBEXPRESSION = 19;
  public int JJTMULTIPLYEXPRESSION = 20;
  public int JJTDIVISIONEXPRESSION = 21;
  public int JJTMODEXPRESSION = 22;
  public int JJTNEGATEEXPRESSION = 23;
  public int JJTUNARYEXPRESSIONNOT = 24;
  public int JJTPROPERTYREADEXPRESSION = 25;
  public int JJTINDEXPROPERTYREADEXPRESSION = 26;
  public int JJTCALLEXPRESSION = 27;
  public int JJTCALLPARAMETERSEXPRESSION = 28;
  public int JJTREFERENCE = 29;


  public String[] jjtNodeName = {
    "BooleanLiteral",
    "NullLiteral",
    "StringLiteral",
    "NumberLiteral",
    "void",
    "Identifier",
    "Expression",
    "SetExpression",
    "SetItemExpression",
    "TernaryExpression",
    "OrExpression",
    "AndExpression",
    "EqualsExpression",
    "NotEqualsExpression",
    "LesserExpression",
    "GreaterExpression",
    "LesserEqualsExpression",
    "GreaterEqualsExpression",
    "AddExpression",
    "SubExpression",
    "MultiplyExpression",
    "DivisionExpression",
    "ModExpression",
    "NegateExpression",
    "UnaryExpressionNot",
    "PropertyReadExpression",
    "IndexPropertyReadExpression",
    "CallExpression",
    "CallParametersExpression",
    "Reference",
  };
}
/* JavaCC - OriginalChecksum=4cbfdc3b4b9db13dd27019e72dd523f1 (do not edit this line) */
