/* Generated By:JavaCC: Do not edit this line. AstParserTreeConstants.java Version 6.0_1 */
package org.lmind.jel.core.ast;

public interface AstParserTreeConstants
{
  public int JJTBOOLEANLITERAL = 0;
  public int JJTNULLLITERAL = 1;
  public int JJTLITERAL = 2;
  public int JJTIDENTIFIER = 3;
  public int JJTVOID = 4;
  public int JJTTERNARYEXPRESSION = 5;
  public int JJTCONDITIONALOREXPRESSION = 6;
  public int JJTCONDITIONALANDEXPRESSION = 7;
  public int JJTEQUALITYEXPRESSION = 8;
  public int JJTRELATIONALEXPRESSION = 9;
  public int JJTADDITIVEEXPRESSION = 10;
  public int JJTMULTIPLICATIVEEXPRESSION = 11;
  public int JJTUNARYEXPRESSIONSIGN = 12;
  public int JJTUNARYEXPRESSIONNOT = 13;
  public int JJTINVOCATIONEXPRESSION = 14;
  public int JJTINDEXPROPERTY = 15;
  public int JJTINVOKEEXPRESSION = 16;
  public int JJTINVOKEPARAMEXPRESSION = 17;
  public int JJTREFERENCE = 18;
  public int JJTMEMBERACCESS = 19;
  public int JJTPARSER = 20;


  public String[] jjtNodeName = {
    "BooleanLiteral",
    "NullLiteral",
    "Literal",
    "Identifier",
    "void",
    "TernaryExpression",
    "ConditionalOrExpression",
    "ConditionalAndExpression",
    "EqualityExpression",
    "RelationalExpression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpressionSign",
    "UnaryExpressionNot",
    "InvocationExpression",
    "IndexProperty",
    "InvokeExpression",
    "InvokeParamExpression",
    "Reference",
    "MemberAccess",
    "parser",
  };
}
/* JavaCC - OriginalChecksum=fb18e6f8d380b1b8cc10f8fcd40aa2e6 (do not edit this line) */
