/* Generated By:JavaCC: Do not edit this line. AstParserTreeConstants.java Version 6.0_1 */
package org.lmind.jel.core.ast;

public interface AstParserTreeConstants
{
  public int JJTBOOLEANLITERAL = 0;
  public int JJTNULLLITERAL = 1;
  public int JJTSTRINGLITERAL = 2;
  public int JJTNUMBERLITERAL = 3;
  public int JJTVOID = 4;
  public int JJTIDENTIFIER = 5;
  public int JJTEXPRESSION = 6;
  public int JJTTERNARYEXPRESSION = 7;
  public int JJTCONDITIONALOREXPRESSION = 8;
  public int JJTCONDITIONALANDEXPRESSION = 9;
  public int JJTEQUALITYEXPRESSION = 10;
  public int JJTRELATIONALEXPRESSION = 11;
  public int JJTADDITIVEEXPRESSION = 12;
  public int JJTMULTIPLICATIVEEXPRESSION = 13;
  public int JJTUNARYEXPRESSIONSIGN = 14;
  public int JJTUNARYEXPRESSIONNOT = 15;
  public int JJTINVOCATIONEXPRESSION = 16;
  public int JJTINDEXPROPERTY = 17;
  public int JJTINVOKEEXPRESSION = 18;
  public int JJTINVOKEPARAMEXPRESSION = 19;
  public int JJTREFERENCE = 20;
  public int JJTMEMBERACCESS = 21;


  public String[] jjtNodeName = {
    "BooleanLiteral",
    "NullLiteral",
    "StringLiteral",
    "NumberLiteral",
    "void",
    "Identifier",
    "Expression",
    "TernaryExpression",
    "ConditionalOrExpression",
    "ConditionalAndExpression",
    "EqualityExpression",
    "RelationalExpression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpressionSign",
    "UnaryExpressionNot",
    "InvocationExpression",
    "IndexProperty",
    "InvokeExpression",
    "InvokeParamExpression",
    "Reference",
    "MemberAccess",
  };
}
/* JavaCC - OriginalChecksum=a9801a661ad9b34c800cf66865504e5b (do not edit this line) */
