/* Generated By:JavaCC: Do not edit this line. AstParserTreeConstants.java Version 6.0_1 */
package org.lmind.jel.core.ast;

public interface AstParserTreeConstants
{
  public int JJTBOOLEANLITERAL = 0;
  public int JJTNULLLITERAL = 1;
  public int JJTLITERAL = 2;
  public int JJTIDENTIFIER = 3;
  public int JJTEXPRESSION = 4;
  public int JJTTERM = 5;
  public int JJTADDITIVEEXPRESSION = 6;
  public int JJTMULTIPLICATIVEEXPRESSION = 7;
  public int JJTUNARYEXPRESSION = 8;
  public int JJTINVOCATIONEXPRESSION = 9;
  public int JJTINDEXPROPERTY = 10;
  public int JJTINVOKEEXPRESSION = 11;
  public int JJTINVOKEPARAMEXPRESSION = 12;
  public int JJTPRIMARYEXPRESSION = 13;
  public int JJTREFERENCE = 14;
  public int JJTMEMBERACCESS = 15;
  public int JJTPARSER = 16;


  public String[] jjtNodeName = {
    "BooleanLiteral",
    "NullLiteral",
    "Literal",
    "Identifier",
    "Expression",
    "Term",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "InvocationExpression",
    "IndexProperty",
    "InvokeExpression",
    "InvokeParamExpression",
    "PrimaryExpression",
    "Reference",
    "MemberAccess",
    "parser",
  };
}
/* JavaCC - OriginalChecksum=737aa0a9e0611e5f79ef9fc5092a0ac4 (do not edit this line) */
